# To be run from within the FactomCode project.

language: go

go:
  - 1.5.3

branches:
  only:
    - Hotfix7

install:
 - go get -t -v ../FactomCode/factomd
 - go get -t -v ../fctwallet
 - go get -t -v ../factom-cli
 - go get -t -v ../walletapp
 - go get github.com/axw/gocov/gocov
 - go get gopkg.in/matm/v1/gocov-html
 - ./all-travis.sh Hotfix7 master


