# To be run from within the FactomCode project.

language: go

go:
  - 1.5.3

branches:
  only:
    - master
    - Hotfix6
    - m2
    - m2s

install:
 - go get -t -v ../FactomCode/factomd
 - go get -t -v ../fctwallet
 - go get -t -v ../factom-cli
 - go get -t -v ../walletapp


